### ISSUE TITLE
MySQL source reads all data into a memory (instead of iterative streaming)

### ISSUE THREAD

**Issue by ateska** [TeskaLabs/bspump#12]

**Comment by ateska** [comment]
May switch to:

class SSCursor(Cursor):
    """Unbuffered Cursor, mainly useful for queries that return a lot of
    data, or for connections to remote servers over a slow network.
    Instead of copying every row of data into a buffer, this will fetch
    rows as needed. The upside of this, is the client uses much less memory,
    and rows are returned much faster when traveling over a slow network,
    or if the result set is very big.
    There are limitations, though. The MySQL protocol doesn't support
    returning the total number of rows, so the only way to tell how many rows
    there are is to iterate over every row returned. Also, it currently isn't
    possible to scroll backwards, as only the current row is held in memory.
    """


https://github.com/aio-libs/aiomysql/blob/fcde0a484f012cad2e31aac7b66b80bbb44a0207/aiomysql/cursors.py#L551

**Comment by mpavelka** [comment]
Created branch `bug#12`

**Comment by mpavelka** [comment]
As per commit `e0a174a`, SSCursor is now the cursor class used in MySQL source. It now needs to be tested on large dataset.
